### PR TITLE
bump tonic,prost

### PR DESCRIPTION
**Pull request by aviramha**

### CODE REVIEW

**Comment by kflansburg** [comment]
Hmmm, wonder why the tests aren't running. Does this build? I though I encountered some issues the last time I updated.

**Comment by kflansburg** [comment]
Oh, I think the build was misconfigured, would you mind re-opening the PR to trigger it now?

**Comment by aviramha** [comment]
seems to fail again

**Review by kflansburg — APPROVED** [review]
Thanks for getting this to work!

**Pull request merged**
